listening-port=3478
tls-listening-port=5349
lt-cred-mech
use-auth-secret
static-auth-secret=d7b63e52-6085-4de0-9602-37e88ee7f695
external-ip=$RAILWAY_PUBLIC_IP
listening-ip=0.0.0.0
relay-ip=0.0.0.0
verbose
fingerprint
no-cli
min-port=49152
max-port=65535
loopback-peers=allowed
