listening-port=3478
listening-ip=0.0.0.0
external-ip=blacklink-turn.fly.dev
lt-cred-mech
use-auth-secret
static-auth-secret=8xR9mK2pQ7vN4wL6yH3jF1sD5gB0tZ9cX7vM2nP4qR6wS8yU0
realm=fly.dev
verbose
fingerprint
min-port=49152
max-port=65535
